repos:
    - repo: https://github.com/0xYYY/foundry-pre-commit
      rev: v1.0.0
      hooks:
          - id: format
            files: \.(sol|s?css|js|ts|jsx|tsx|json|ya?ml|html|md)$
            types_or: [file]
            pass_filenames: true
          