name: Test Coverage

on:
  workflow_dispatch:

jobs:
  check:
    name: Forge Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.0.0

      - name: Run coverage
        run: forge coverage --report lcov --no-match-contract "(EthereumForkTest|ArbitrumForkTest)"

      - name: Install lcov
        run: sudo apt-get update && sudo apt-get install -y lcov

      - name: Filter out everything except src folder
        run: lcov --extract lcov.info "src/*" --output-file lcov.info --ignore-errors inconsistent

      - name: Generate HTML coverage report
        run: genhtml -o coverage_html lcov.info --ignore-errors inconsistent

      - name: Upload coverage HTML report
        uses: actions/upload-artifact@v4
        with:
          name: forge-coverage-html
          path: coverage_html/