name: Foundry CI

# Trigger the workflow on any push or pull request to the main branch, or when manually triggered
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Step 2: Install Foundry
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      # Step 3: Run Forge Build
      - name: Build with Forge
        run: forge build --sizes

      # Step 4: Run Forge Tests
      - name: Run Tests with Forge
        run: forge test -vvv
