name: Slither Analysis

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v0.3.0

      - name: Compile Contracts
        run: forge build --force --build-info --out out

      - name: Run Slither
        uses: crytic/slither-action@v0.4.0
        with:
          solc-version: 0.8.28
          slither-args: --foundry-out-directory out
          fail-on: high
