name: Slither Analysis

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Slither
        uses: crytic/slither-action@v0.4.0
        with:
          slither-args: --foundry-version v0.3.0
          fail-on: high
